### ISSUE TITLE
Est-ce un bug, je n'en suis pas sûr car ne suis qu'un débutant en impression 3D

### ISSUE THREAD

**Issue by AndroSteph** [Dtcreation/Firmware-Molise-TFT#10]
Une fois le filament chargé, apparaît à l'écran un message avec "PurgeMore" ou Continue", sur la version 5.0 que je viens de mettre (je n'ai pas testé sur la 4.8, désolé), en appuyant sur "PurgeMore" rien ne se passe et l'écran revient toujours au même affichage avec "Paused" affiché au milieu, si j'appuie sur "Continue", c'est OK l'écran passe à un autre affichage et je refais un "Load" pour purger une deuxième fois.

**Comment by Dtcreation** [comment]
Le bug est résolu avec la 5.1 ?

**Comment by AndroSteph** [comment]
Pas encore testé car je suis en train de poser des rails linéaires sur les 3 axes, donc X1 démontée pour l'instant, désolé de ne pouvoir répondre.

**Comment by AndroSteph** [comment]
Idem avec la version 5.1

**Comment by AndroSteph** [comment]
toujours idem avec la version 5.2

**Comment by Dtcreation** [comment]
Je n'arrive pas à reproduire le problème sur mes deux machines

**Comment by AndroSteph** [comment]
Je en sais pas quoi dire, 5.0 et 5.1 avec l'extruder d'origine et maintenant la 5.2 avec un extruder BMG.
Bon, ce n'est pas vraiment problématique, je fais juste un "reload" et j'ai à nouveau du filament qui sort.

**Comment by AndroSteph** [comment]
Avec la mise à jour de Molise en 2.1.1 ... ce problème n'est plus présent :-)

Bonne journée à tous !
