### ISSUE TITLE
[BUG] Purge more fail at filament change time

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-TFT#7]
### Description
If you change filament with printing paused, you can use purge more function.

At print resume time, the extruder will resume position and so go back all the extra length.

### Steps to reproduce

1. Pause print
2. Unload
3. Load
4. Purge more
5. Resume
When runing resume, you can see how filament is "unloaded".

**Expected behavior**
Extruder should consider that the position at resume time is inline with the position as pause time.

**Comment by eiffel31** [comment]
I made a more simple test: simple filament change using unload/load.
Load does automatically purge, but the filament movement is reverted when the print resumes. So significant amount of plastic is missing in the print at each filament change.

**Comment by Dtcreation** [comment]
Hi,

This bug must be resolved in the last release  4.8
