### ISSUE TITLE
[FR] Silent mode

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-TFT#8]
**Is your feature request related to a problem? Please describe.**
On Sidewinder X1, motors are silent or noisy depending on the speed.
A button on the screen to switch silent mode on/off would be great.
Some examples:
- you want to make a phone call, to watch the TV, to sleep: activate the silent mode.
- the phone call is finished, you leave the room...: go back to full speed

**Describe the solution you'd like**
There is a clear speed threshold where a whistling noise appears.
Below this limit, the motors are quiet and silent (even if some resonance may create vibrating noise at some specific speeds).
Just above the limit, an additional noise is created.

The idea is to add a silent mode toggle button on the screen.

I tested the SW-X1 up to the limits. According to my experiments, I propose to use these values:
When silent mode is pressed: M203 X158 Y158 Z30 E26 ; above these limits, an additional noise appears
When silent mode is OFF: M203 X483 Y483 Z90 E75 ; above these limits, the motors are not able to run

**Additional context**
A switch similar to BL ON/OFF would be great, with easy access while running.
A reminder of the current mode on the main screen would be fine.
May be related to the speed adjustment screen. This button may replace the "normal" button.

**Comment by eiffel31** [comment]
In performance mode, Z90 is not always safe (stepper motors can skip steps).
I suggest a reduced limit:
M203 X483 Y483 Z85 E75

**Comment by Dtcreation** [comment]
Hello,

Hybrid threshold is not activated in Molise since version 1.3.0 i guess

**Comment by eiffel31** [comment]
I am using 1.3.2
I have no idea if the noise difference is related to hybrid threshold or not. I just observed that above some limit, a whistling appear.
