### ISSUE TITLE
[BUG] Power Loss recovery fails

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-TFT#9]
### Description
With X1 TFT firmware 4.8, Power Loss recovery does not work.
At recovery time, it locks on reading process.

### Steps to reproduce

Printing using USB memory key.

3 times, my printer crashed with a failure
Each time, after reboot, the printer was not able to continue the print.

Note: as PL recovery was working fine with previous version, I made a try.
For the third print, the printer crashed (this is due to a temperature sensor failure and I expect PID code crashes with unexpected values).
After the restart, it was unable to continue the print. The screen is locked on the loading screen. Many attempts gave the very same result.
Then, I flashed firmware 4.7
Restarted the printer with the USB memory key.
I was able to successfully continue the print! I saved my print with limited damages due to bed temperature lowered when interrupted.

So firmware 4.7 is able to continue some print started with 4.8
4.8 is not able to continue it's own print.

**Comment by Dtcreation** [comment]
Bonjour,

Corrigé dans la dernière version

**Comment by eiffel31** [comment]
Merci

J'ai pour l'instant un problème de sonde de température du bed. Je ferai un essai de la nouvelle version dès que la machine sera à nouveau opérationnelle.
